language: node_js
node_js: lts/*
os:
  - windows
  - linux
  - osx

jobs:
  include:
    - stage: Produce Coverage
      node_js: lts/*
      os: linux
      script: npm run coveralls
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - 'npm run release'

branches:
  only:
    - master
